{
  _config:: {},
  apiVersion: "v1",
  binaryData: {
    localtime: "VFppZjIAAAAAAAAAAAAAAAAAAAAAAAADAAAAAwAAAAAAAAARAAAAAwAAAAyAAAAAyFwBgMj6J3DJ1Q6Aytta8B66NgAfaX9wIH5ogCFJYXAiXkqAIylDcCRHZwAlEl/wJidJACbyQfAoBysAKNIj8AIBAgECAQIBAgECAQIBAgECAABx1wAAAAB+kAEEAABwgAAITE1UAENEVABDU1QAAAAAAAAAVFppZjIAAAAAAAAAAAAAAAAAAAAAAAADAAAAAwAAAAAAAAASAAAAAwAAAAz4AAAAAAAAAP////9+NkMp/////8hcAYD/////yPoncP/////J1Q6A/////8rbWvAAAAAAHro2AAAAAAAfaX9wAAAAACB+aIAAAAAAIUlhcAAAAAAiXkqAAAAAACMpQ3AAAAAAJEdnAAAAAAAlEl/wAAAAACYnSQAAAAAAJvJB8AAAAAAoBysAAAAAACjSI/AAAgECAQIBAgECAQIBAgECAQIAAHHXAAAAAH6QAQQAAHCAAAhMTVQAQ0RUAENTVAAAAAAAAAAKQ1NULTgK",
  },
  kind: "ConfigMap",
  metadata: {
    name: "timezone-beijing",
    namespace: $._config.namespaces.console,
  },
}
